### ISSUE TITLE
 Storm's testing facilities Integration 

### ISSUE THREAD

**Issue by stonegao** [colinsurprenant/redstorm#11]
Storm will expose its testing facilities to Java API, it's only available in clojure currently. ( https://github.com/nathanmarz/storm/issues/72 ). 

Testing is indispensable for writing reliable storm topologies. So redstorm should integrate the testing facilities of Storm once it's available. 

For the time being, @nathanmarz suggest that using Clojure for the test. Any suggestions on Clojure & JRuby interop, so we can using the  testing facilities?

**Comment by stonegao** [comment]
FYI: Ben ( @schleyfox ) wrote a library for storm testing in clojure.  

https://github.com/schleyfox/storm-test

With two blog posts about testing storm topologies: 

http://www.pixelmachine.org/2011/12/17/Testing-Storm-Topologies.html
http://www.pixelmachine.org/2011/12/21/Testing-Storm-Topologies-Part-2.html

**Comment by schleyfox** [comment]
I really didn't write much, most of storm's testing functionality is available within the standard distribution.

You could try https://github.com/kyleburton/jrclj for a jruby to clojure bridge.

**Comment by nathanmarz** [comment]
@stonegao I'd be curious to hear if you're successful in leveraging Storm's testing facilities through that bridge.

**Comment by colinsurprenant** [comment]
Sorry for the delay, but I will be taking a look at what can be done to help with testing. @stonegao let me know if you have made any more investigations with this.

**Comment by stonegao** [comment]
Busy with other stuff at the moment, will begin active developing our system based on redstorm later this month. I 'll let you know the findings.

**Comment by colinsurprenant** [comment]
per https://github.com/nathanmarz/storm/issues/72 Storm 0.8.1 now exposes its testing facilities.

**Comment by kb** [comment]
Has any additional thought been put into this from a Redstorm perspective? Any examples out there?

**Comment by colinsurprenant** [comment]
I started to play a bit with the Storm testing Java API and it seems a no brainer to use from JRuby + RSpec. I will make some example tests.

**Comment by colinsurprenant** [comment]
I created the redstorm-starter https://github.com/colinsurprenant/redstorm-starter/ project which provides example specs for bolts and complete topology using the Storm testing API.

**Comment by kb** [comment]
Really helpful! I'll let you know if I run into any issues.
