### ISSUE TITLE
Switch Logger To SLF4J

### ISSUE THREAD

**Issue by arielvalentin** [colinsurprenant/redstorm#110]
Storm has moved to [SLF4J with logback|http://storm.incubator.apache.org/2013/12/08/storm090-released.html], however Redstorm uses the Log4J API. I would like to be able to use SLF4J API instead of any specific implementation in my topologies.

**Comment by colinsurprenant** [comment]
Absolutely, thanks for pointing that out.

**Comment by arielvalentin** [comment]
I have run into the Ruby Exceptions aren't Java Exceptions problem. Looks like @dekellum solved this by adding an adapter API in rjack-slf4j https://github.com/dekellum/rjack/blob/dev/slf4j/lib/rjack-slf4j.rb

Should we consider using this approach instead?

**Comment by colinsurprenant** [comment]
what is the Ruby Exceptions aren't Java Exceptions problem and how did it manifest?

**Comment by arielvalentin** [comment]
I hope these comments make sense. I am exhausted. 

[RubyException](http://jruby.org/apidocs/org/jruby/RubyException.html) does not inherit from [Throwable](http://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html). I used the overloaded error method assuming it was matching [error(string, throwable)](http://www.slf4j.org/apidocs/org/slf4j/Logger.html#error%28java.lang.String,%20java.lang.Throwable%29) but it actually resolved to [error(string, object)](http://www.slf4j.org/apidocs/org/slf4j/Logger.html#error%28java.lang.String,%20java.lang.Object%29). 

I then started thinking about what it would take to use the logger with gems. It was then I realized the APIs would not line up e.g. what if someone tried to use the [block](http://www.ruby-doc.org/stdlib-2.1.2/libdoc/logger/rdoc/Logger.html#method-i-info) to delay interpretation of the log message. In this case we would need an object that conformed to the API of a Ruby Logger. That's what made me think of rjack. I did pose the question to the JRuby list and was directed at a few other gems but haven't really looked into them.   

The differences in the Logger APIs made us converge on using the [error(string)](http://www.slf4j.org/apidocs/org/slf4j/Logger.html#error%28java.lang.String%29) method and just generate the message using a helper function.
