### ISSUE TITLE
Support Logging Named Hierarchies 

### ISSUE THREAD

**Issue by arielvalentin** [colinsurprenant/redstorm#111]
When trying to configure logback system I am unable to use the named hierarchy feature because they use dots, however Ruby class names have double colons:

``` ruby```
@log ||= Java::OrgSlf4j::LoggerFactory.get_logger(self.name) 
```

One way to fix this is to substitute colons with dots:

``` ruby
 @log ||= Java::OrgSlf4j::LoggerFactory.get_logger(self.name.gsub(/::/,'.')) 
```

Then then one could register the loggers like this:

``` xml```
  <logger name="Example.Project" >
    <appender-ref ref="ASYNC_SYSLOG"/>
  </logger>
```

**Comment by colinsurprenant** [comment]
Again(!) thanks for the hint! 
relates to #110
