### ISSUE TITLE
Support for Ruby autoload

### ISSUE THREAD

**Issue by arielvalentin** [colinsurprenant/redstorm#113]
I tried to use Ruby autoload when creating modules in my topology however I run into LoadErrors because the LOAD_PATH does not seem to include the packaged "lib" directory. I tried adding the directory manually but it does not work in the cluster.

**Comment by colinsurprenant** [comment]
ah, never tried using autoload in a topology, will have to trace the problem. so it works in local but not in cluster?

**Comment by arielvalentin** [comment]
I did not try in local mode. I'll give that a try and let you know.

Thanks,

## Ariel
