### ISSUE TITLE
Tick tuple config not working

### ISSUE THREAD

**Issue by benmoss** [colinsurprenant/redstorm#114]
I found @colinsurprenant's answer for how to implement the tick tuple [here](http://stackoverflow.com/questions/22547705/implement-storm-tick-tuple-in-redstorm-dsl), but it no longer seems to work. 

I just get `org.jruby.exceptions.RaiseException: (NameError) uninitialized constant Java::BacktypeStorm::Config::TOPOLOGY_TICK_TUPLE_FREQ_SECS`. I've tried to debug this and reflect on the class, and while it does seem to have some of the methods from the Java Config class, it is missing a lot. Not sure if this is just a limitation of JRuby's reflection, or what might be going on here.

Using RedStorm 0.6.6 and JRuby 1.7.13

**Comment by colinsurprenant** [comment]
hmm... not sure but this is maybe a version incompatibility, I don't remember with which version I tested this but it might have been with the 0.7.0.beta1. do you think you could test this with this version?

**Comment by adamgotterer** [comment]
I believe tick tuples weren't implemented until Storm 0.8.0

**Comment by benmoss** [comment]
Yep, that is exactly the problem @colinsurprenant. Works on 0.7.0-beta1.
