### ISSUE TITLE
0.3.0 release?

### ISSUE THREAD

**Issue by Jell** [colinsurprenant/redstorm#12]
Any chance of seeing red storm 0.3.0 being released on rubygems?

The documentation says that running `gem install redstorm` will install redstorm 0.3.0, but it is still 0.2.1 that is the latest release available.

**Comment by colinsurprenant** [comment]
Yes, sorry about this delay, I just got back from a 3 weeks climbing trip without much connectivity :P. I am catching up, should be done shortly.

**Comment by colinsurprenant** [comment]
I decided not release a gem for 0.3.0 and go to 0.4.0 with the integration of Storm 0.6.2 and JRuby 1.6.6. It is available now.

If you really need a 0.3.0, I created the tag v0.3.0 which includes your fixes. You can build the gem from it.

**Comment by Jell** [comment]
That's perfect! Thanks!
