### ISSUE TITLE
Update Storm dependency to .9.2-incubating

### ISSUE THREAD

**Issue by svrana** [colinsurprenant/redstorm#120]
I currently have a .9.2-incubating storm cluster but have topologies built against .9.1-incubating. This leaves something to be desired, so I'm hoping to be able to update redstorm (and my topologies) to build against Storm .9.2-incubating.

The first thing I noticed after upgrading to build against .9.2-incubating was a method signature change to the StormSubmitter.submitTopology. It now takes a ProgressListener parameter (see https://github.com/apache/incubator-storm/blob/master/storm-core/src/jvm/backtype/storm/StormSubmitter.java#L86).

There may well be other problems. I will document them here as I find them.

**Comment by svrana** [comment]
Having problems getting my topology unit tests to pass after upgrading to have them build against .9.2; Storm is timing them out after 5 seconds. The error message looks like this: Java::JavaLang::AssertionError:Test timed out (5000ms) This is just too short on my aging laptop (and on our Jenkins boxen, for that matter). Fortunately the timeout was made configurable here: https://github.com/apache/incubator-storm/pull/122  Alas, this change is not in the current .9.2-incubating build available from Apache.  This makes me a little less interested in pursuing an update of redstorm to depend on .9.2 at this time, as I'd have to maintain a custom build of storm just to run tests.

Having said all that, with the simple change mentioned in my previous comment, redstorm builds against .9.2 and can submit topologies and runs just fine. See https://github.com/svrana/redstorm/commit/801fd74bea4bcbd5f11b8885673fe3304c0cedd4

**Comment by colinsurprenant** [comment]
thanks @svrana for your feedback on this. 
it is a bit puzzling as of why they didn't just keep the `submitTopology` method signature without the `ProgressListener` and just add another signature with the `ProgressListener`. Weird.
I just reviewed the 0.9.2 announcement and there does not seem to be any api changes so it should just work.

**Comment by ismith** [comment]
"it is a bit puzzling as of why they didn't just keep the submitTopology method signature without the ProgressListener and just add another signature with the ProgressListener. Weird."

Maybe it's worth opening a https://issues.apache.org/jira/browse/STORM ticket?  Seems regression-like to me.  (I don't have an Apache Jira account, although I could open one next week and file.)

**Comment by colinsurprenant** [comment]
agree. will try if I have time tomorrow before my flight...

**Comment by relwell** [comment]
Did anything ever happen on this one? It looks like they reintroduced this API in 0.9.3, so I'm wondering if it makes sense to keep this open?
