### ISSUE TITLE
add storm 0.7.0 support

### ISSUE THREAD

**Issue by stonegao** [colinsurprenant/redstorm#20]
storm 0.7.0 already released : https://groups.google.com/forum/#!topic/storm-user/Z24Yka01Vyw/discussion

**Comment by colinsurprenant** [comment]
This is my next step, I will add 0.7.x support. I just updated master with support for bundler and Ruby 1.9 mode (and JRuby 1.6.7).

**Comment by colinsurprenant** [comment]
Storm 0.7.1 added and working well in master. About to release gem v0.5.0 with this.
