### ISSUE TITLE
TopologyLauncher does not run in Ruby 1.9 in the 19mode branch

### ISSUE THREAD

**Issue by danharvey** [colinsurprenant/redstorm#21]
Using the 19mode branch when you run `storm jar ...` it will run the TopologyLauncher using Ruby 1.8 by default which will in turn run your topology configuration script in ruby 1.8 rather than 1.9 even if you've got JRUBY_OTPS=--1.9 set from the environment you deploy from.

To fix this we need to set the JVM property -Djruby.compat.version=RUBY1_9 before we run the TopologyLauncher. This has to be done by storm whilst it creates the command to call `java ....`, if there isn't another way to do this we should file a ticket with the main storm project to add support for this.

Modifying storm this locally I've found this to work.

**Comment by colinsurprenant** [comment]
Hey, I know its been a while but just to let you know that I finally merged my 19mode and bundler branches and 1.9 is working correctly in master. The README is updated with all relevant information for the master branch. I have not yet published the gem but you can build it yourself locally or checkout master and run your topologies directly from the project. 

Also, late thanks for the heads up :P

**Comment by colinsurprenant** [comment]
If you still use RedStorm you might want to take a look at the latest 0.6.0 - 1.8/1.9 Ruby mode is now correctly handled from end-to-end, local and cluster mode. By default, the 1.8/1.9 Ruby mode of the current interpreter will be correctly propagated to the local or cluster topology (can also be forced using --1.8 or --1.9 switch).
