### ISSUE TITLE
redstorm install fails when using --verbose flags

### ISSUE THREAD

**Issue by kovacs** [colinsurprenant/redstorm#3]
When I run "redstorm install" I get the following error when it gets to the first jruby compile statement:

--> Compiling JRuby
/Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/1.8/optparse.rb:1451:in `complete': invalid option: --verbose (OptionParser::InvalidOption)
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/1.8/optparse.rb:1449:in`catch'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/1.8/optparse.rb:1449:in `complete'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/1.8/optparse.rb:1262:in`parse_in_order'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/1.8/optparse.rb:1255:in `catch'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/1.8/optparse.rb:1255:in`parse_in_order'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/1.8/optparse.rb:1249:in `order!'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/1.8/optparse.rb:1340:in`permute!'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/1.8/optparse.rb:1361:in `parse!'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/site_ruby/shared/jruby/compiler.rb:74:in`compile_argv'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/1.8/optparse.rb:792:in `initialize'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/site_ruby/shared/jruby/compiler.rb:34:in`new'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/lib/ruby/site_ruby/shared/jruby/compiler.rb:34:in `compile_argv'
    from /Users/mkovacs/.rvm/rubies/jruby-1.5.6/bin/jrubyc:9

Pulling the --verbose out of the jrubyc and out of the javac fixes things for me. Not sure why it's breaking for me... I'm running java 1.6 and jruby 1.5.6 as you see in the output.

**Comment by colinsurprenant** [comment]
I haven't tested RedStorm with JRuby versions prior to 1.6. This is certainly a problem with jrubyc not supporting this option. Is there any reason why you don't upgrade your JRuby to 1.6.5?

**Comment by kovacs** [comment]
Oh dang.. I didn't even notice that! I thought I had the latest version :-) swapped the 5 and 6
