### ISSUE TITLE
Don't shell out unless absolutely necessary

### ISSUE THREAD

**Issue by iconara** [colinsurprenant/redstorm#32]
When running the Redstorm tasks there's a lot of shelling out going on. Redstorm shells out to rmvn, which, IIRC, shells out to mvn. Shelling out is very slow on the JVM, and doubly so since all the processes started are also JVMs. It feels unnecessary and can probably be sped up considerably if all the work was done in-process.

Perhaps the dependency management could be done with [Pom Pom Pom](https://github.com/iconara/pompompom) instead? It uses Ivy under the hood, has a simple programmatic API (even experimental Bundler integration), and does everything in-process. (Full disclosure: I'm the author, if you hadn't guessed already).

I haven't published a gem for v2 yet, v1 is very old and not very good. If you don't like the idea, perhaps I could help just rewriting the dependency management parts using Ivy directly?

**Comment by colinsurprenant** [comment]
Hi Theo,

Thanks for the suggestion. I agree the current process is suboptimal. I like your idea and you are very welcome to try and improve the dependency management with pompompoma and ivy! 

Colin

**Comment by iconara** [comment]
I'll see what I can do.

**Comment by colinsurprenant** [comment]
solved in issue #33
