### ISSUE TITLE
Storm UI

### ISSUE THREAD

**Issue by steventen** [colinsurprenant/redstorm#34]
Hi, is there a way that I can use storm ui through ruby? And if it's local mode. Can I still use it?

**Comment by colinsurprenant** [comment]
Hi,

the Storm UI  is actually independent from RedStorm, it must be started from the Storm distribution and will only monitor a cluster/remote environment. Storm UI does not work with a local cluster.

If you want to use a topology on a cluster/remote environment, you must evidently have a Storm cluster setup. You also need the Storm distribution locally for you to submit the topology to the cluster. 

Please let me know if that does not answer your question.

**Comment by steventen** [comment]
Hi Colin,

 thanks for your answer
