### ISSUE TITLE
Manually emitting tuples

### ISSUE THREAD

**Issue by harrigan** [colinsurprenant/redstorm#4]
Suppose I have a a bolt that does not auto-emit. How do I manually emit a tuple using your DSL? For example,

``` ruby
class MyBolt < RedStorm::SimpleBolt
  output_fields :my_output_field

  on_receive :emit => false do |tuple|
    ...
    unanchored_emit ["output-field-value"] # also tried without the square brackets
  end
end
```

results in the following error:

```
10934 [Thread-38] ERROR backtype.storm.util  - Async loop died!
java.lang.NullPointerException
  at backtype.storm.tuple.Tuple.<init>(Tuple.java:43)
```

Should the above work? Also, should the DSL have an "emit" keyword seeing as the bolt is already specified as unanchored (by default).

BTW, great work on the DSL.

**Comment by harrigan** [comment]
Sorry, the error above was being raised by another bolt :-(

unanchored_emit does indeed work.

**Comment by colinsurprenant** [comment]
love these bugs ;)

note that you can alternatively call the "native" Java emit method on the collector if need be using:

``` ruby
collector.emit(Values.new(value1, ...)
collector.emit(tuple, Values.new(value1, ...)
```

the `config`, `context` and `collector` are exposed in spouts and bolts post-init (post-open & post-prepare in Java). 

Thanks,
Colin
