### ISSUE TITLE
add support for Distributed RPC

### ISSUE THREAD

**Issue by mikeclymer** [colinsurprenant/redstorm#42]
I do not currently see a way to handle DRPC in RedStorm. DSL / proxy support for LinearDRPCTopologyBuilder and related DRPC classes would be very useful.

**Comment by colinsurprenant** [comment]
Absolutely. LinearDRPCTopologyBuilder with topology submission support should be fairly easy to add.

**Comment by colinsurprenant** [comment]
DRPC support has been added in 0.6.5.
