### ISSUE TITLE
redstorm should support namespaced class definition

### ISSUE THREAD

**Issue by stonegao** [colinsurprenant/redstorm#5]
I tried add namespace to word_count_topology.rb in examples/simple/ : 

``` ruby
require 'examples/simple/random_sentence_spout'
require 'examples/simple/split_sentence_bolt'
require 'examples/simple/word_count_bolt'
module Example
  module Simple
    class WordCountTopology < RedStorm::SimpleTopology
      spout RandomSentenceSpout, :parallelism => 5

      bolt SplitSentenceBolt, :parallelism => 8 do
        source RandomSentenceSpout, :shuffle
      end

      bolt WordCountBolt, :parallelism => 12 do
        source SplitSentenceBolt, :fields => ["word"]
      end

      configure :word_count do |env|
        case env
        when :local
          debug true
          max_task_parallelism 3
        when :cluster
          debug true
          num_workers 20
          max_spout_pending(1000);
        end
      end

      on_submit do |env|
        if env == :local
          sleep(5)
          cluster.shutdown
        end
      end
    end

  end
end

```

But after adding namespace, redstorm can't find WordCountTopology anymore. For real projects, we need to use namespace to organize code, so redstorm should support namespaced class definition.

<pre>
stone-laptop:redstorm-try stone$ redstorm local examples/simple/word_count_topology.rb 
launching java -cp "/Users/stone/tmp/redstorm-try/target/classes:/Users/stone/tmp/redstorm-try/target/dependency/*" redstorm.TopologyLauncher local examples/simple/word_count_topology.rb
file:/Users/stone/tmp/redstorm-try/target/dependency/jruby-complete-1.6.5.jar!/builtin/javasupport/core_ext/object.rb:99 warning: already initialized constant Config
RedStorm v0.2.1 starting topology WordCountTopology in local environment
1    [main] ERROR org.apache.zookeeper.server.NIOServerCnxn  - Thread Thread[main,5,main] died
org.jruby.exceptions.RaiseException: (NameError) uninitialized constant WordCountTopology
        at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:2590)
        at #<Class:0x4ab34646>.(eval)((eval):1)
        at org.jruby.RubyModule.module_eval(org/jruby/RubyModule.java:2246)
        at #<Class:0x3f2221f6>.main(/Users/stone/.rvm/gems/jruby-1.6.5/gems/redstorm-0.2.0/lib/red_storm/topology_launcher.rb:43)

</pre>

**Comment by colinsurprenant** [comment]
Hi Stone,

Yes, it was a design tradeoff. Passing only the filename of the topology class to the launcher & inferring the topology class name from the filename seemed the simplest route but the tradeoff is that the topology class must be visible at the top level. But this is only true with the topology class, other classes like spouts and bolts can be namespaced.

Sooo... I am not sure what would be the best/simplest way to solve this... maybe find a way that upon topology class declaration, it could register itself (namespaced class) into a global singleton configuration object and the launcher could use that info to instantiate the topology class? I'll try this to see if that would work.

suggestions? 

Colin

**Comment by stonegao** [comment]
how about pass the Topology with its namespace directly ? Like the following:

```
redstorm local Example::Simple::WordCountTopology examples/simple/word_count_topology.rb 
```

**Comment by colinsurprenant** [comment]
ok, this is fixed in the topology_namespace branch, just have to add a few specs then I'll merge into master. No usage changes when using the DSL.
