### ISSUE TITLE
Update RedStorm to target Storm 0.8

### ISSUE THREAD

**Issue by fractaloop** [colinsurprenant/redstorm#50]
RedStorm currently targets 0.7.4 right now. Storm is up to 0.8.1 with 0.8.2 to be release soon. It adds some awesome features I'm sure a lot of RedStorm users would appreciate.

As it stands, I've been using RedStorm with 0.8.0 and 0.8.1 and it seems to work alright.

**Comment by colinsurprenant** [comment]
On it. I will first close 0.6.3 today then do another release with update to Storm 0.8.1 and JRuby 1.6.8 and make sure nothing breaks with the current codebase. After that I will work on Trident support.

**Comment by grinser** [comment]
Awesome :)

**Comment by colinsurprenant** [comment]
all tests are passing with Storm 0.8.1 and JRuby 1.6.8, looking good. In branch v0.6.4.

**Comment by fractaloop** [comment]
Woot!
