### ISSUE TITLE
`redstorm bundle` fails to load git based gems

### ISSUE THREAD

**Issue by fractaloop** [colinsurprenant/redstorm#51]
**Updated**

Only gems from RubyGems will work when bundling a topology. If a gem is from a git repo, the .gemspec will not be compiled like the ones from RubyGems. As a result, it will fail to load.

Steps to reproduce:

``` ruby
# Gemfile
group :topology do
  gem 'multi_json', git: 'https://github.com/intridea/multi_json.git'
end
```

`bundle exec redstorm bundle topology`

Then attempt to run the topology locally to get a LoadError.

**Comment by colinsurprenant** [comment]
interesting... seems I never tried to `redstorm bundle` with --deployment bundles... I'll have to check!

**Comment by colinsurprenant** [comment]
I am not able to reproduce the problem. I tried doing `bundle package` and then a `bundle install --deployment` and `redstorm bundle topology` just worked...

Could give me more information about your setup, maybe a minimal sample project and the steps to reproduce? Also could you give me a dump of the error?

**Comment by fractaloop** [comment]
Updated with actual cause of issue.

**Comment by colinsurprenant** [comment]
Ok, good catch. I'll see how we can deal with this.
