### ISSUE TITLE
make topology class configure statement optional

### ISSUE THREAD

**Issue by thbar** [colinsurprenant/redstorm#56]
I'm writing my first topology, so beware :-)

When running it, I got:

```
launching java -Djruby.compat.version=RUBY1_9 -cp "/Users/thbar/git/project/storm-prototype/target/classes:/Users/thbar/git/project/storm-prototype/target/dependency/storm/default/*:/Users/thbar/git/project/storm-prototype/target/dependency/topology/default/*:/Users/thbar/git/project/storm-prototype/" redstorm.TopologyLauncher local simple_topology.rb
SLF4J: The requested version 1.5.8 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
0    [main] ERROR org.apache.zookeeper.server.NIOServerCnxn  - Thread Thread[main,5,main] died
org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `name' for nil:NilClass
  at (Anonymous).main(/Users/thbar/.rvm/gems/jruby-1.7.0@project/gems/redstorm-0.6.4/lib/red_storm/topology_launcher.rb:42)
```

The work-around is to add a `configure` block: do we need a better error handling here, if configure is actually required?

**Comment by thbar** [comment]
Sidenote: the SLF4J warning got me thinking if I needed to fix something or not.

**Comment by colinsurprenant** [comment]
Good catch!! I am quite surprised this one has not surfaced earlier. Need to add better specs for the topology definition handling. 

Right, you can ignore the SLF4J warnings. This is an annoying dependency issue which is basically harmless and does not affect cluster mode.

**Comment by thbar** [comment]
Beginner's eyes :-)

Thanks for the precision on SLF4J!
