### ISSUE TITLE
Adding Support Multiple Source in RedStrom DSL's Bolt

### ISSUE THREAD

**Issue by palanglung** [colinsurprenant/redstorm#59]
![Storm Topology](http://storm-project.net/images/topology.png)

Implement Multiple Source so we can do this in our topology with redstorm

**Comment by colinsurprenant** [comment]
it should actually work out-of-the-box simply by declaring multiple source statements in the topology bolt definition, for example:

``` ruby
bolt SomeBolt do
  source Bolt1, :shuffle
  source Bolt2, :shuffle
end
```

Did you try this?

**Comment by palanglung** [comment]
Yes Its working i create some spec somehow but forgot to rebase so i close that issue maybe this issue also might be closed.

are you already create the spec? if not maybe i can re push the spec.

**Comment by colinsurprenant** [comment]
yes! you should make a pull request for your specs, I will include them. thanks!
