### ISSUE TITLE
redstorm use absolute path for generated Java proxy classes

### ISSUE THREAD

**Issue by stonegao** [colinsurprenant/redstorm#6]
For generated Java proxy classes in target/src/redstorm/ ( TopologyLauncher.java, proxy/{Bolt.java, Spout.java} )

I noticed in the generated source code, it use absolute path, will this cause error when deployed to other machines?

``` java
  __ruby__.executeScript(source, "/Users/stone/.rvm/gems/jruby-1.6.5/gems/redstorm-0.2.1/lib/red_storm/proxy/spout.rb");
  __ruby__.executeScript(source, "/Users/stone/.rvm/gems/jruby-1.6.5/gems/redstorm-0.2.1/lib/red_storm/proxy/bolt.rb");
  __ruby__.executeScript(source, "/Users/stone/.rvm/gems/jruby-1.6.5/gems/redstorm-0.2.1/lib/red_storm/topology_launcher.rb"); 
```

**Comment by colinsurprenant** [comment]
Hi Stone,

Good catch. I am not sure about the implications of this, but it doesn't seem to be a problem when deploying a topology on a remote production cluster that do not have these paths...  I will investigate.

**Comment by colinsurprenant** [comment]
AFAICT looking a the JRuby source code, this filename string is only for information purposes (exceptions, strack trace, etc) so it does not affect the running code, locally of remotely on a production cluster.

**Comment by stonegao** [comment]
Thanks for your findings.
