### ISSUE TITLE
JRubyShellSpout is in wrong package

### ISSUE THREAD

**Issue by dmuir** [colinsurprenant/redstorm#64]
I installed redstorm-0.6.4 from rubygems, and am having trouble setting up a shell spout.  It looks like the package for JRubyShellSpout is backtype.storm.clojure, but the simple topology is expecting it to be redstorm.storm.jruby.

I'd submit a pull request to fix this, but he other issue is that I can't seem to find JRubyShellSpout.java or JRubyShellBolt.java in the GitHub repo, though they exist in my installed gems.

**Comment by colinsurprenant** [comment]
could you gist your setup so I can take a look at it? also, take a look at `examples/shell/shell_topology.rb` - last time I check it was working ok.

**Comment by dmuir** [comment]
That doesn't use a shell spout, just a shell bolt.  The issue is
specifically with shell spouts.

-Doug

On Wed, Mar 20, 2013 at 11:25 AM, Colin Surprenant <notifications@github.com

**Comment by colinsurprenant** [comment]
ah! sorry about that. so you are right, I just checked the source in `src/main/redstorm/storn/jruby/JRubyShellSpout.java` and it defines 

```
package backtype.storm.clojure;
```

In the mean time you should be able to do:

```
java_import 'backtype.storm.clojure.JRubyShellBolt'
```

This will be fixed for the next release. Feel free to submit a pull request.

**Comment by colinsurprenant** [comment]
you were right, both JRubyShellSpout.java and JRubyShellBolt.java were not in the repo, because of a bug in my .gitignore. I had them locally in my src tree but they were never committed in the repo. it is fixed now in master.

thanks for your help with this.
