### ISSUE TITLE
document snakeyaml jar conflict workaround with Storm 0.8.2 and JRuby 1.7.3

### ISSUE THREAD

**Issue by colinsurprenant** [colinsurprenant/redstorm#78]
problem reported and workaround from @kb.
also reported in Storm issues https://github.com/nathanmarz/storm/pull/567
also problem reproduction gist https://github.com/kb/redstorm-tester/blob/master/tester/tester.rb

basically snakeyaml must be updated to 1.11 in the Storm distribution. It is possible to do so in the RedStorm Ivy dependencies file but will only solve the problem when running local topologies. For clusters, it must be done outside RedStorm.

**Comment by colinsurprenant** [comment]
documented in README

**Comment by kb** [comment]
Merged into master and appears to be in the current WIP release https://github.com/nathanmarz/storm/pull/567

**Comment by colinsurprenant** [comment]
nice!
