### ISSUE TITLE
java.lang.NoClassDefFoundError: org/jruby/runtime/Helpers

### ISSUE THREAD

**Issue by palanglung** [colinsurprenant/redstorm#80]
Log :

1 [main] ERROR org.apache.zookeeper.server.NIOServerCnxn - Thread Thread[main,5,main] died
java.lang.NoClassDefFoundError: org/jruby/runtime/Helpers
at redstorm.TopologyLauncher.main(TopologyLauncher.java:146)
Caused by: java.lang.ClassNotFoundException: org.jruby.runtime.Helpers
at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
... 1 more

$ ruby -v
jruby 1.7.3 (1.9.3p385) 2013-02-21 dac429b on OpenJDK 64-Bit Server VM 1.7.0_21-b02 [linux-amd64]

$ ls target/dependency/topology/default/jruby-*
jruby-core-1.7.3.jar jruby-stdlib-1.7.3.jar

$ redstorm version
RedStorm v0.6.5

$ storm version
0.8.2

if you found problem something like this make sure you have exactly the same jruby version and try to reproduce all generated file it will solved the problem

**Comment by tarcieri** [comment]
I'm running into this issue as well...

**Comment by tarcieri** [comment]
I downgraded to JRuby 1.7.2 and this corrected the problem

**Comment by colinsurprenant** [comment]
(sorry for not updating the issue, the resolution was via email and I forgot to update here :P) 

for @palanglung the problem was related to a JRuby mismatch between his local JRuby 1.7.4 and the JRuby used in the RedStorm 0.6.5 dependency which is 1.7.3. 

The best way to fix this is to create a "custom" topology dependency:  `ivy/topology_dependencies.xml` with the following:

``` xml
<?xml version="1.0"?>
<ivy-module version="2.0">
<info organisation="redstorm" module="topology-deps"/>
<dependencies>
<dependency org="org.jruby" name="jruby-core" rev="1.7.4" conf="default" transitive="true"/>
</dependencies>
</ivy-module>
```

and then rebuild all

``` sh
$ rm -rf target 
$ redstorm install
```

**Comment by palanglung** [comment]
@colinsurprenant actualy yes it solve but i am forgot to put detail to reproduce when i updating the issue before :)
