### ISSUE TITLE
How do I run in 1.9 mode?

### ISSUE THREAD

**Issue by iconara** [colinsurprenant/redstorm#9]
I can't find a way to run my code in 1.9 mode, I only get 1.8.7. Setting `JRUBY_OPTS` has no effect. Is there any way to get RedStorm to run the Ruby code in 1.9?

**Comment by colinsurprenant** [comment]
right. I did a quick try early in the project it's a bit tricky, in particular with remote clusters. Let me see if I can at least provide a quick hack so you can test that.

**Comment by colinsurprenant** [comment]
Hi Theo,

just a quick note that I got it working in both local mode and on remote cluster (using JRuby 1.6.6 and Storm 0.6.2). It is now possible to specify 1.8 ou 1.9 mode per topology. It is available in the [19mode branch](https://github.com/colinsurprenant/redstorm/tree/19mode)

In local mode, simply add either --1.8 or --1.9 when launching and for remote cluster add

```
set("topology.worker.childopts", "-Djruby.compat.version=RUBY1_9")
```

in the topology configure block. See the [RubyVersionTopology](https://github.com/colinsurprenant/redstorm/blob/19mode/examples/simple/ruby_version_topology.rb) which you can use to test as it simply output the current RUBY_VERSION string.

I just need to clean this a bit then I'll do a formal release.

**Comment by iconara** [comment]
very nice! thanks a lot.

T#

**Comment by colinsurprenant** [comment]
1.8/1.9 support is finally merged in master and README has all the gory details :P
