### ISSUE TITLE
InvalidLocaleData

### ISSUE THREAD

**Issue by Rockyyost** [colinsurprenant/redstorm#90]
I'm having an issue with loading a YAML file in Redstorm. When I add the mongoid gem, active support gets added too and when running a topology, I get the following error:

org.jruby.exceptions.RaiseException: (InvalidLocaleData) can not load translations from /Users/Dev/Documents/Projects/Nightingale/storm/target/gems/gems/activesupport-3.2.16/lib/active_support/locale/en.yml: java.lang.NoSuchMethodError: org.yaml.snakeyaml.events.DocumentStartEvent.getVersion()Lorg/yaml/snakeyaml/DumperOptions$Version;

I haven't altered the en.yml file at all and I even tried using the snakeyaml fix located here: https://github.com/colinsurprenant/redstorm#known-issues

I'm still running into the same issue.

Let me know if more information is required.

Thanks!

**Comment by colinsurprenant** [comment]
It is a known snakeyaml conflict between JRuby and Storm, see issue #78 and the workaround is also documented in the README at https://github.com/colinsurprenant/redstorm#known-issues

Let me know if that help you solve it!

**Comment by Rockyyost** [comment]
Thanks for your reply. I tried the workaround, and unless I've implemented it wrong, I'm still getting the error. 

I created the storm_dependencies.xml, copied your code into and then saved the file in the ivy folder where ivy-2.3.0 is.

Was that correct? Is there another step I missed?

Thanks!

**Comment by colinsurprenant** [comment]
you should delete the `target/` directory and redo a `redstorm install` after having updated your `storm_dependencies.xml`. 

let me know if that works.

**Comment by Rockyyost** [comment]
That did it! Thank you so much for your help!

**Comment by colinsurprenant** [comment]
Great! It should be better documented.
